### ISSUE TITLE
data_process疑问

### ISSUE THREAD

**Issue by xiaboAAA** [Zhaozixiang1228/IF-FILM#3]
赵博士您好，请问在数据预处理时，报如下错误：
Traceback (most recent call last):
  File "data_process.py", line 87, in <module>
    img_B = cv2.resize(image_read_cv2(os.path.join(img_text_path, 'Image', task_name, dataset_name, 'vi', sample_name + '.png'), mode='GRAY'), small_size_0)[None, ...] / 255.0
  File "/home/lyu/Data/A_code3/IF-FILM-main/utils/img_read_save.py", line 7, in image_read_cv2
    img_BGR = cv2.imread(path).astype('float32')
AttributeError: 'NoneType' object has no attribute 'astype'
我该如何解决呢？我已经按照data_process.py的数据集格式，放在了相应位置。非常感谢您的回答。

**Comment by jaytchen** [comment]
May I ask you how this problem was solved?
